name: Test Docusaurus Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - "my-docs/**"
      - ".github/workflows/test.yml"

jobs:
  test-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-docs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: my-docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Mivel docs/petstore ki van .gitignore-olva, PR check alatt is gener√°ljuk
      - name: Generate OpenAPI docs
        run: npx docusaurus gen-api-docs petstore

      - name: Build
        run: npm run build
